/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthGoogleTestRouteImport } from './routes/auth.google-test'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoEmbedRouteImport } from './routes/demo.embed'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as SurveyTokenRouteImport } from './routes/survey.$token'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminOwnersRouteImport } from './routes/_authenticated/admin_.owners'
import { Route as AuthenticatedOnboardingOwnerRouteImport } from './routes/_authenticated/onboarding.owner'
import { Route as AuthenticatedOwnerAnalyticsRouteImport } from './routes/_authenticated/owner_.analytics'
import { Route as AuthenticatedOwnerContactRouteImport } from './routes/_authenticated/owner_.contact'
import { Route as AuthenticatedOwnerDiagnosticsRouteImport } from './routes/_authenticated/owner_.diagnostics'
import { Route as AuthenticatedOwnerFeedbackRouteImport } from './routes/_authenticated/owner_.feedback'
import { Route as AuthenticatedOwnerSubscribeRouteImport } from './routes/_authenticated/owner_.subscribe'
import { Route as AuthenticatedOwnerSupportRouteImport } from './routes/_authenticated/owner_.support'
import { Route as ApiPublicCalendarEventRouteImport } from './routes/api/public/calendar-event'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth.google-calendar.return'
import { Route as ApiPublicEmailsSurveyInviteRouteImport } from './routes/api/public/emails/survey-invite'
import { Route as ApiPublicJobsBookingMaintenanceRouteImport } from './routes/api/public/jobs/booking-maintenance'
import { Route as ApiPublicJobsBuildReportsRouteImport } from './routes/api/public/jobs/build-reports'
import { Route as ApiPublicJobsEnrichFeedbackRouteImport } from './routes/api/public/jobs/enrich-feedback'
import { Route as ApiPublicJobsSendSurveysRouteImport } from './routes/api/public/jobs/send-surveys'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthGoogleTestRoute = AuthGoogleTestRouteImport.update({
  id: '/google-test',
  path: '/google-test',
  getParentRoute: () => AuthRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEmbedRoute = DemoEmbedRouteImport.update({
  id: '/demo/embed',
  path: '/demo/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOwnersRoute =
  AuthenticatedAdminOwnersRouteImport.update({
    id: '/admin_/owners',
    path: '/admin/owners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingOwnerRoute =
  AuthenticatedOnboardingOwnerRouteImport.update({
    id: '/onboarding/owner',
    path: '/onboarding/owner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerAnalyticsRoute =
  AuthenticatedOwnerAnalyticsRouteImport.update({
    id: '/owner_/analytics',
    path: '/owner/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerContactRoute =
  AuthenticatedOwnerContactRouteImport.update({
    id: '/owner_/contact',
    path: '/owner/contact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerDiagnosticsRoute =
  AuthenticatedOwnerDiagnosticsRouteImport.update({
    id: '/owner_/diagnostics',
    path: '/owner/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerFeedbackRoute =
  AuthenticatedOwnerFeedbackRouteImport.update({
    id: '/owner_/feedback',
    path: '/owner/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerSubscribeRoute =
  AuthenticatedOwnerSubscribeRouteImport.update({
    id: '/owner_/subscribe',
    path: '/owner/subscribe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerSupportRoute =
  AuthenticatedOwnerSupportRouteImport.update({
    id: '/owner_/support',
    path: '/owner/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCalendarEventRoute = ApiPublicCalendarEventRouteImport.update({
  id: '/api/public/calendar-event',
  path: '/api/public/calendar-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailsSurveyInviteRoute =
  ApiPublicEmailsSurveyInviteRouteImport.update({
    id: '/api/public/emails/survey-invite',
    path: '/api/public/emails/survey-invite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsBookingMaintenanceRoute =
  ApiPublicJobsBookingMaintenanceRouteImport.update({
    id: '/api/public/jobs/booking-maintenance',
    path: '/api/public/jobs/booking-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsBuildReportsRoute =
  ApiPublicJobsBuildReportsRouteImport.update({
    id: '/api/public/jobs/build-reports',
    path: '/api/public/jobs/build-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsEnrichFeedbackRoute =
  ApiPublicJobsEnrichFeedbackRouteImport.update({
    id: '/api/public/jobs/enrich-feedback',
    path: '/api/public/jobs/enrich-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsSendSurveysRoute =
  ApiPublicJobsSendSurveysRouteImport.update({
    id: '/api/public/jobs/send-surveys',
    path: '/api/public/jobs/send-surveys',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/barber': typeof BarberRoute
  '/mcp': typeof McpRoute
  '/owners': typeof OwnersRoute
  '/provider': typeof ProviderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/auth/google-test': typeof AuthGoogleTestRoute
  '/demo/embed': typeof DemoEmbedRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/owners': typeof AuthenticatedAdminOwnersRoute
  '/onboarding/owner': typeof AuthenticatedOnboardingOwnerRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/contact': typeof AuthenticatedOwnerContactRoute
  '/owner/diagnostics': typeof AuthenticatedOwnerDiagnosticsRoute
  '/owner/feedback': typeof AuthenticatedOwnerFeedbackRoute
  '/owner/subscribe': typeof AuthenticatedOwnerSubscribeRoute
  '/owner/support': typeof AuthenticatedOwnerSupportRoute
  '/api/public/calendar-event': typeof ApiPublicCalendarEventRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/emails/survey-invite': typeof ApiPublicEmailsSurveyInviteRoute
  '/api/public/jobs/booking-maintenance': typeof ApiPublicJobsBookingMaintenanceRoute
  '/api/public/jobs/build-reports': typeof ApiPublicJobsBuildReportsRoute
  '/api/public/jobs/enrich-feedback': typeof ApiPublicJobsEnrichFeedbackRoute
  '/api/public/jobs/send-surveys': typeof ApiPublicJobsSendSurveysRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/barber': typeof BarberRoute
  '/mcp': typeof McpRoute
  '/owners': typeof OwnersRoute
  '/provider': typeof ProviderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/auth/google-test': typeof AuthGoogleTestRoute
  '/demo/embed': typeof DemoEmbedRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/demo': typeof DemoIndexRoute
  '/shop': typeof ShopIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/owners': typeof AuthenticatedAdminOwnersRoute
  '/onboarding/owner': typeof AuthenticatedOnboardingOwnerRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/contact': typeof AuthenticatedOwnerContactRoute
  '/owner/diagnostics': typeof AuthenticatedOwnerDiagnosticsRoute
  '/owner/feedback': typeof AuthenticatedOwnerFeedbackRoute
  '/owner/subscribe': typeof AuthenticatedOwnerSubscribeRoute
  '/owner/support': typeof AuthenticatedOwnerSupportRoute
  '/api/public/calendar-event': typeof ApiPublicCalendarEventRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/emails/survey-invite': typeof ApiPublicEmailsSurveyInviteRoute
  '/api/public/jobs/booking-maintenance': typeof ApiPublicJobsBookingMaintenanceRoute
  '/api/public/jobs/build-reports': typeof ApiPublicJobsBuildReportsRoute
  '/api/public/jobs/enrich-feedback': typeof ApiPublicJobsEnrichFeedbackRoute
  '/api/public/jobs/send-surveys': typeof ApiPublicJobsSendSurveysRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/barber': typeof BarberRoute
  '/mcp': typeof McpRoute
  '/owners': typeof OwnersRoute
  '/provider': typeof ProviderRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/auth/google-test': typeof AuthGoogleTestRoute
  '/demo/embed': typeof DemoEmbedRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/demo/': typeof DemoIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin_/owners': typeof AuthenticatedAdminOwnersRoute
  '/_authenticated/onboarding/owner': typeof AuthenticatedOnboardingOwnerRoute
  '/_authenticated/owner_/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/_authenticated/owner_/contact': typeof AuthenticatedOwnerContactRoute
  '/_authenticated/owner_/diagnostics': typeof AuthenticatedOwnerDiagnosticsRoute
  '/_authenticated/owner_/feedback': typeof AuthenticatedOwnerFeedbackRoute
  '/_authenticated/owner_/subscribe': typeof AuthenticatedOwnerSubscribeRoute
  '/_authenticated/owner_/support': typeof AuthenticatedOwnerSupportRoute
  '/api/public/calendar-event': typeof ApiPublicCalendarEventRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/emails/survey-invite': typeof ApiPublicEmailsSurveyInviteRoute
  '/api/public/jobs/booking-maintenance': typeof ApiPublicJobsBookingMaintenanceRoute
  '/api/public/jobs/build-reports': typeof ApiPublicJobsBuildReportsRoute
  '/api/public/jobs/enrich-feedback': typeof ApiPublicJobsEnrichFeedbackRoute
  '/api/public/jobs/send-surveys': typeof ApiPublicJobsSendSurveysRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/barber'
    | '/mcp'
    | '/owners'
    | '/provider'
    | '/reset-password'
    | '/shop'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/owner'
    | '/auth/google-test'
    | '/demo/embed'
    | '/shop/$slug'
    | '/survey/$token'
    | '/demo/'
    | '/shop/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/owners'
    | '/onboarding/owner'
    | '/owner/analytics'
    | '/owner/contact'
    | '/owner/diagnostics'
    | '/owner/feedback'
    | '/owner/subscribe'
    | '/owner/support'
    | '/api/public/calendar-event'
    | '/api/public/health'
    | '/api/public/ready'
    | '/oauth/google-calendar/return'
    | '/api/public/emails/survey-invite'
    | '/api/public/jobs/booking-maintenance'
    | '/api/public/jobs/build-reports'
    | '/api/public/jobs/enrich-feedback'
    | '/api/public/jobs/send-surveys'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/barber'
    | '/mcp'
    | '/owners'
    | '/provider'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/owner'
    | '/auth/google-test'
    | '/demo/embed'
    | '/shop/$slug'
    | '/survey/$token'
    | '/demo'
    | '/shop'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/owners'
    | '/onboarding/owner'
    | '/owner/analytics'
    | '/owner/contact'
    | '/owner/diagnostics'
    | '/owner/feedback'
    | '/owner/subscribe'
    | '/owner/support'
    | '/api/public/calendar-event'
    | '/api/public/health'
    | '/api/public/ready'
    | '/oauth/google-calendar/return'
    | '/api/public/emails/survey-invite'
    | '/api/public/jobs/booking-maintenance'
    | '/api/public/jobs/build-reports'
    | '/api/public/jobs/enrich-feedback'
    | '/api/public/jobs/send-surveys'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/barber'
    | '/mcp'
    | '/owners'
    | '/provider'
    | '/reset-password'
    | '/shop'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/_authenticated/owner'
    | '/auth/google-test'
    | '/demo/embed'
    | '/shop/$slug'
    | '/survey/$token'
    | '/demo/'
    | '/shop/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin_/owners'
    | '/_authenticated/onboarding/owner'
    | '/_authenticated/owner_/analytics'
    | '/_authenticated/owner_/contact'
    | '/_authenticated/owner_/diagnostics'
    | '/_authenticated/owner_/feedback'
    | '/_authenticated/owner_/subscribe'
    | '/_authenticated/owner_/support'
    | '/api/public/calendar-event'
    | '/api/public/health'
    | '/api/public/ready'
    | '/oauth/google-calendar/return'
    | '/api/public/emails/survey-invite'
    | '/api/public/jobs/booking-maintenance'
    | '/api/public/jobs/build-reports'
    | '/api/public/jobs/enrich-feedback'
    | '/api/public/jobs/send-surveys'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BarberRoute: typeof BarberRoute
  McpRoute: typeof McpRoute
  OwnersRoute: typeof OwnersRoute
  ProviderRoute: typeof ProviderRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DemoEmbedRoute: typeof DemoEmbedRoute
  SurveyTokenRoute: typeof SurveyTokenRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCalendarEventRoute: typeof ApiPublicCalendarEventRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicEmailsSurveyInviteRoute: typeof ApiPublicEmailsSurveyInviteRoute
  ApiPublicJobsBookingMaintenanceRoute: typeof ApiPublicJobsBookingMaintenanceRoute
  ApiPublicJobsBuildReportsRoute: typeof ApiPublicJobsBuildReportsRoute
  ApiPublicJobsEnrichFeedbackRoute: typeof ApiPublicJobsEnrichFeedbackRoute
  ApiPublicJobsSendSurveysRoute: typeof ApiPublicJobsSendSurveysRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/google-test': {
      id: '/auth/google-test'
      path: '/google-test'
      fullPath: '/auth/google-test'
      preLoaderRoute: typeof AuthGoogleTestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/embed': {
      id: '/demo/embed'
      path: '/demo/embed'
      fullPath: '/demo/embed'
      preLoaderRoute: typeof DemoEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/owners': {
      id: '/_authenticated/admin_/owners'
      path: '/admin/owners'
      fullPath: '/admin/owners'
      preLoaderRoute: typeof AuthenticatedAdminOwnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/owner': {
      id: '/_authenticated/onboarding/owner'
      path: '/onboarding/owner'
      fullPath: '/onboarding/owner'
      preLoaderRoute: typeof AuthenticatedOnboardingOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner_/analytics': {
      id: '/_authenticated/owner_/analytics'
      path: '/owner/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof AuthenticatedOwnerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner_/contact': {
      id: '/_authenticated/owner_/contact'
      path: '/owner/contact'
      fullPath: '/owner/contact'
      preLoaderRoute: typeof AuthenticatedOwnerContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner_/diagnostics': {
      id: '/_authenticated/owner_/diagnostics'
      path: '/owner/diagnostics'
      fullPath: '/owner/diagnostics'
      preLoaderRoute: typeof AuthenticatedOwnerDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner_/feedback': {
      id: '/_authenticated/owner_/feedback'
      path: '/owner/feedback'
      fullPath: '/owner/feedback'
      preLoaderRoute: typeof AuthenticatedOwnerFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner_/subscribe': {
      id: '/_authenticated/owner_/subscribe'
      path: '/owner/subscribe'
      fullPath: '/owner/subscribe'
      preLoaderRoute: typeof AuthenticatedOwnerSubscribeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner_/support': {
      id: '/_authenticated/owner_/support'
      path: '/owner/support'
      fullPath: '/owner/support'
      preLoaderRoute: typeof AuthenticatedOwnerSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/calendar-event': {
      id: '/api/public/calendar-event'
      path: '/api/public/calendar-event'
      fullPath: '/api/public/calendar-event'
      preLoaderRoute: typeof ApiPublicCalendarEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emails/survey-invite': {
      id: '/api/public/emails/survey-invite'
      path: '/api/public/emails/survey-invite'
      fullPath: '/api/public/emails/survey-invite'
      preLoaderRoute: typeof ApiPublicEmailsSurveyInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/booking-maintenance': {
      id: '/api/public/jobs/booking-maintenance'
      path: '/api/public/jobs/booking-maintenance'
      fullPath: '/api/public/jobs/booking-maintenance'
      preLoaderRoute: typeof ApiPublicJobsBookingMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/build-reports': {
      id: '/api/public/jobs/build-reports'
      path: '/api/public/jobs/build-reports'
      fullPath: '/api/public/jobs/build-reports'
      preLoaderRoute: typeof ApiPublicJobsBuildReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/enrich-feedback': {
      id: '/api/public/jobs/enrich-feedback'
      path: '/api/public/jobs/enrich-feedback'
      fullPath: '/api/public/jobs/enrich-feedback'
      preLoaderRoute: typeof ApiPublicJobsEnrichFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/send-surveys': {
      id: '/api/public/jobs/send-surveys'
      path: '/api/public/jobs/send-surveys'
      fullPath: '/api/public/jobs/send-surveys'
      preLoaderRoute: typeof ApiPublicJobsSendSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedAdminOwnersRoute: typeof AuthenticatedAdminOwnersRoute
  AuthenticatedOnboardingOwnerRoute: typeof AuthenticatedOnboardingOwnerRoute
  AuthenticatedOwnerAnalyticsRoute: typeof AuthenticatedOwnerAnalyticsRoute
  AuthenticatedOwnerContactRoute: typeof AuthenticatedOwnerContactRoute
  AuthenticatedOwnerDiagnosticsRoute: typeof AuthenticatedOwnerDiagnosticsRoute
  AuthenticatedOwnerFeedbackRoute: typeof AuthenticatedOwnerFeedbackRoute
  AuthenticatedOwnerSubscribeRoute: typeof AuthenticatedOwnerSubscribeRoute
  AuthenticatedOwnerSupportRoute: typeof AuthenticatedOwnerSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedAdminOwnersRoute: AuthenticatedAdminOwnersRoute,
  AuthenticatedOnboardingOwnerRoute: AuthenticatedOnboardingOwnerRoute,
  AuthenticatedOwnerAnalyticsRoute: AuthenticatedOwnerAnalyticsRoute,
  AuthenticatedOwnerContactRoute: AuthenticatedOwnerContactRoute,
  AuthenticatedOwnerDiagnosticsRoute: AuthenticatedOwnerDiagnosticsRoute,
  AuthenticatedOwnerFeedbackRoute: AuthenticatedOwnerFeedbackRoute,
  AuthenticatedOwnerSubscribeRoute: AuthenticatedOwnerSubscribeRoute,
  AuthenticatedOwnerSupportRoute: AuthenticatedOwnerSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthGoogleTestRoute: typeof AuthGoogleTestRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGoogleTestRoute: AuthGoogleTestRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BarberRoute: BarberRoute,
  McpRoute: McpRoute,
  OwnersRoute: OwnersRoute,
  ProviderRoute: ProviderRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DemoEmbedRoute: DemoEmbedRoute,
  SurveyTokenRoute: SurveyTokenRoute,
  DemoIndexRoute: DemoIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCalendarEventRoute: ApiPublicCalendarEventRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicEmailsSurveyInviteRoute: ApiPublicEmailsSurveyInviteRoute,
  ApiPublicJobsBookingMaintenanceRoute: ApiPublicJobsBookingMaintenanceRoute,
  ApiPublicJobsBuildReportsRoute: ApiPublicJobsBuildReportsRoute,
  ApiPublicJobsEnrichFeedbackRoute: ApiPublicJobsEnrichFeedbackRoute,
  ApiPublicJobsSendSurveysRoute: ApiPublicJobsSendSurveysRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
