-- Intentionally empty.
--
-- This migration was an exact duplicate of
-- 20260816174023_survey_invites_and_enrichment_metadata.sql. Keep the version
-- in migration history, but do not replay the same CREATE TABLE statements.
