-- Intentionally empty.
--
-- This migration was an exact duplicate of
-- 20260816182918_subscriptions_and_analytics_gating.sql. Keep the version in
-- migration history, but do not replay the same CREATE TABLE statements.
